export const inventoryData = [
  {
    serialNo: "INV-001",
    productName: "MacBook Pro 16-inch",
    brandName: "Apple",
    quantityAvailable: 15,
    category: "Electronics",
    pricePerQuantity: 2499.99,
  },
  {
    serialNo: "INV-002",
    productName: "ThinkPad X1 Carbon",
    brandName: "Lenovo",
    quantityAvailable: 8,
    category: "Electronics",
    pricePerQuantity: 1899.99,
  },
  {
    serialNo: "INV-003",
    productName: "Office Chair Ergonomic",
    brandName: "Herman Miller",
    quantityAvailable: 25,
    category: "Furniture",
    pricePerQuantity: 899.99,
  },
  {
    serialNo: "INV-004",
    productName: "Standing Desk",
    brandName: "IKEA",
    quantityAvailable: 12,
    category: "Furniture",
    pricePerQuantity: 299.99,
  },
  {
    serialNo: "INV-005",
    productName: "Wireless Mouse",
    brandName: "Logitech",
    quantityAvailable: 45,
    category: "Accessories",
    pricePerQuantity: 79.99,
  },
  {
    serialNo: "INV-006",
    productName: "Mechanical Keyboard",
    brandName: "Corsair",
    quantityAvailable: 0,
    category: "Accessories",
    pricePerQuantity: 149.99,
  },
  {
    serialNo: "INV-007",
    productName: "4K Monitor 27-inch",
    brandName: "Dell",
    quantityAvailable: 6,
    category: "Electronics",
    pricePerQuantity: 599.99,
  },
  {
    serialNo: "INV-008",
    productName: "Printer Laser",
    brandName: "HP",
    quantityAvailable: 3,
    category: "Electronics",
    pricePerQuantity: 399.99,
  },
  {
    serialNo: "INV-009",
    productName: "Conference Table",
    brandName: "Steelcase",
    quantityAvailable: 4,
    category: "Furniture",
    pricePerQuantity: 1299.99,
  },
  {
    serialNo: "INV-010",
    productName: "Webcam HD",
    brandName: "Logitech",
    quantityAvailable: 18,
    category: "Accessories",
    pricePerQuantity: 129.99,
  },
  {
    serialNo: "INV-011",
    productName: "iPad Pro 12.9-inch",
    brandName: "Apple",
    quantityAvailable: 22,
    category: "Electronics",
    pricePerQuantity: 1099.99,
  },
  {
    serialNo: "INV-012",
    productName: "Desk Lamp LED",
    brandName: "Philips",
    quantityAvailable: 35,
    category: "Accessories",
    pricePerQuantity: 89.99,
  },
  {
    serialNo: "INV-013",
    productName: "Surface Pro 9",
    brandName: "Microsoft",
    quantityAvailable: 9,
    category: "Electronics",
    pricePerQuantity: 1299.99,
  },
  {
    serialNo: "INV-014",
    productName: "Bookshelf",
    brandName: "IKEA",
    quantityAvailable: 7,
    category: "Furniture",
    pricePerQuantity: 199.99,
  },
  {
    serialNo: "INV-015",
    productName: "Headphones Noise-Canceling",
    brandName: "Sony",
    quantityAvailable: 14,
    category: "Accessories",
    pricePerQuantity: 349.99,
  },
]
